package com.example.tokenserver.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.util.List;

/**
 * Response body for all /register endpoints.
 * Represents OBClientRegistration1 with client_id guaranteed to be present.
 */
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ClientRegistrationResponse {

    // Generated by the server on registration
    @JsonProperty("client_id")
    private String clientId;

    @JsonProperty("client_secret")
    private String clientSecret;

    @JsonProperty("client_id_issued_at")
    private Integer clientIdIssuedAt;

    @JsonProperty("client_secret_expires_at")
    private Integer clientSecretExpiresAt;

    // OBClientRegistration1 JWT claims
    @JsonProperty("iss")
    private String iss;

    @JsonProperty("iat")
    private Integer iat;

    @JsonProperty("exp")
    private Integer exp;

    @JsonProperty("aud")
    private String aud;

    @JsonProperty("jti")
    private String jti;

    // OBRegistrationProperties1 fields
    @JsonProperty("redirect_uris")
    private List<String> redirectUris;

    @JsonProperty("token_endpoint_auth_method")
    private String tokenEndpointAuthMethod;

    @JsonProperty("grant_types")
    private List<String> grantTypes;

    @JsonProperty("response_types")
    private List<String> responseTypes;

    @JsonProperty("software_id")
    private String softwareId;

    @JsonProperty("scope")
    private String scope;

    @JsonProperty("software_statement")
    private String softwareStatement;

    @JsonProperty("application_type")
    private String applicationType;

    @JsonProperty("id_token_signed_response_alg")
    private String idTokenSignedResponseAlg;

    @JsonProperty("request_object_signing_alg")
    private String requestObjectSigningAlg;

    @JsonProperty("token_endpoint_auth_signing_alg")
    private String tokenEndpointAuthSigningAlg;

    @JsonProperty("tls_client_auth_subject_dn")
    private String tlsClientAuthSubjectDn;

    @JsonProperty("backchannel_token_delivery_mode")
    private String backchannelTokenDeliveryMode;

    @JsonProperty("backchannel_client_notification_endpoint")
    private String backchannelClientNotificationEndpoint;

    @JsonProperty("backchannel_authentication_request_signing_alg")
    private String backchannelAuthenticationRequestSigningAlg;

    @JsonProperty("backchannel_user_code_parameter_supported")
    private Boolean backchannelUserCodeParameterSupported;

}
